apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-drut
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-drut
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-drut
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-drut
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-drut
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-qayy-tenant/rhtap-demo-app/hacbs-test-project-drut@sha256:3d0c93f94d140dbaecf0402bfb3fec9a1652a877a5482e423d4bcbf8cd0ebf6b
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
