apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-drut
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-qayy-tenant/rhtap-demo-app/hacbs-test-project-drut@sha256:6f61772ddc49f690bb99ccf1eb167aaccf4b9029657518db580bf6ec1ec1b762
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
